// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'panel-copy'
  | 'panel-empty-hint'
  | 'panel-input-hint'
  | 'panel-insert-selection'
  | 'panel-no-selection'
  | 'panel-send'
  | 'panel-stop'
  | 'pref-api-header'
  | 'pref-apikey'
  | 'pref-baseurl'
  | 'pref-context-header'
  | 'pref-enable'
  | 'pref-fulltextlimit'
  | 'pref-help'
  | 'pref-includefulltext'
  | 'pref-maxtokens'
  | 'pref-model'
  | 'pref-quickprompts'
  | 'pref-systemprompt'
  | 'pref-temperature'
  | 'pref-title'
  | 'prefs-title'
  | 'section-chat-header'
  | 'section-chat-sidenav'
  | 'startup-begin'
  | 'startup-finish'
  | 'tooltip-delete'
  | 'tooltip-new';
