// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "baseURL": string;
      "apiKey": string;
      "model": string;
      "temperature": number;
      "maxTokens": number;
      "includeFullText": boolean;
      "fullTextLimit": number;
      "contextWindowTokens": number;
      "systemPrompt": string;
      "quickPrompts": string;
      "agenticResearch": boolean;
      "agenticMaxWorks": number;
    };
  }
}
